/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnVisionRouteImport } from './routes/learn.vision'
import { Route as LearnTransformerRouteImport } from './routes/learn.transformer'
import { Route as LearnTrainingProcessRouteImport } from './routes/learn.training-process'
import { Route as LearnTokenizationRouteImport } from './routes/learn.tokenization'
import { Route as LearnPredictionRouteImport } from './routes/learn.prediction'
import { Route as LearnPositionalEncodingRouteImport } from './routes/learn.positional-encoding'
import { Route as LearnNeuralNetworkRouteImport } from './routes/learn.neural-network'
import { Route as LearnEmbeddingsRouteImport } from './routes/learn.embeddings'
import { Route as LearnAttentionRouteImport } from './routes/learn.attention'

const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnVisionRoute = LearnVisionRouteImport.update({
  id: '/learn/vision',
  path: '/learn/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTransformerRoute = LearnTransformerRouteImport.update({
  id: '/learn/transformer',
  path: '/learn/transformer',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTrainingProcessRoute = LearnTrainingProcessRouteImport.update({
  id: '/learn/training-process',
  path: '/learn/training-process',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTokenizationRoute = LearnTokenizationRouteImport.update({
  id: '/learn/tokenization',
  path: '/learn/tokenization',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnPredictionRoute = LearnPredictionRouteImport.update({
  id: '/learn/prediction',
  path: '/learn/prediction',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnPositionalEncodingRoute = LearnPositionalEncodingRouteImport.update({
  id: '/learn/positional-encoding',
  path: '/learn/positional-encoding',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnNeuralNetworkRoute = LearnNeuralNetworkRouteImport.update({
  id: '/learn/neural-network',
  path: '/learn/neural-network',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnEmbeddingsRoute = LearnEmbeddingsRouteImport.update({
  id: '/learn/embeddings',
  path: '/learn/embeddings',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnAttentionRoute = LearnAttentionRouteImport.update({
  id: '/learn/attention',
  path: '/learn/attention',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/curriculum': typeof CurriculumRoute
  '/learn/attention': typeof LearnAttentionRoute
  '/learn/embeddings': typeof LearnEmbeddingsRoute
  '/learn/neural-network': typeof LearnNeuralNetworkRoute
  '/learn/positional-encoding': typeof LearnPositionalEncodingRoute
  '/learn/prediction': typeof LearnPredictionRoute
  '/learn/tokenization': typeof LearnTokenizationRoute
  '/learn/training-process': typeof LearnTrainingProcessRoute
  '/learn/transformer': typeof LearnTransformerRoute
  '/learn/vision': typeof LearnVisionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/curriculum': typeof CurriculumRoute
  '/learn/attention': typeof LearnAttentionRoute
  '/learn/embeddings': typeof LearnEmbeddingsRoute
  '/learn/neural-network': typeof LearnNeuralNetworkRoute
  '/learn/positional-encoding': typeof LearnPositionalEncodingRoute
  '/learn/prediction': typeof LearnPredictionRoute
  '/learn/tokenization': typeof LearnTokenizationRoute
  '/learn/training-process': typeof LearnTrainingProcessRoute
  '/learn/transformer': typeof LearnTransformerRoute
  '/learn/vision': typeof LearnVisionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/curriculum': typeof CurriculumRoute
  '/learn/attention': typeof LearnAttentionRoute
  '/learn/embeddings': typeof LearnEmbeddingsRoute
  '/learn/neural-network': typeof LearnNeuralNetworkRoute
  '/learn/positional-encoding': typeof LearnPositionalEncodingRoute
  '/learn/prediction': typeof LearnPredictionRoute
  '/learn/tokenization': typeof LearnTokenizationRoute
  '/learn/training-process': typeof LearnTrainingProcessRoute
  '/learn/transformer': typeof LearnTransformerRoute
  '/learn/vision': typeof LearnVisionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/curriculum'
    | '/learn/attention'
    | '/learn/embeddings'
    | '/learn/neural-network'
    | '/learn/positional-encoding'
    | '/learn/prediction'
    | '/learn/tokenization'
    | '/learn/training-process'
    | '/learn/transformer'
    | '/learn/vision'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/curriculum'
    | '/learn/attention'
    | '/learn/embeddings'
    | '/learn/neural-network'
    | '/learn/positional-encoding'
    | '/learn/prediction'
    | '/learn/tokenization'
    | '/learn/training-process'
    | '/learn/transformer'
    | '/learn/vision'
  id:
    | '__root__'
    | '/'
    | '/curriculum'
    | '/learn/attention'
    | '/learn/embeddings'
    | '/learn/neural-network'
    | '/learn/positional-encoding'
    | '/learn/prediction'
    | '/learn/tokenization'
    | '/learn/training-process'
    | '/learn/transformer'
    | '/learn/vision'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CurriculumRoute: typeof CurriculumRoute
  LearnAttentionRoute: typeof LearnAttentionRoute
  LearnEmbeddingsRoute: typeof LearnEmbeddingsRoute
  LearnNeuralNetworkRoute: typeof LearnNeuralNetworkRoute
  LearnPositionalEncodingRoute: typeof LearnPositionalEncodingRoute
  LearnPredictionRoute: typeof LearnPredictionRoute
  LearnTokenizationRoute: typeof LearnTokenizationRoute
  LearnTrainingProcessRoute: typeof LearnTrainingProcessRoute
  LearnTransformerRoute: typeof LearnTransformerRoute
  LearnVisionRoute: typeof LearnVisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/vision': {
      id: '/learn/vision'
      path: '/learn/vision'
      fullPath: '/learn/vision'
      preLoaderRoute: typeof LearnVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/transformer': {
      id: '/learn/transformer'
      path: '/learn/transformer'
      fullPath: '/learn/transformer'
      preLoaderRoute: typeof LearnTransformerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/training-process': {
      id: '/learn/training-process'
      path: '/learn/training-process'
      fullPath: '/learn/training-process'
      preLoaderRoute: typeof LearnTrainingProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/tokenization': {
      id: '/learn/tokenization'
      path: '/learn/tokenization'
      fullPath: '/learn/tokenization'
      preLoaderRoute: typeof LearnTokenizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/prediction': {
      id: '/learn/prediction'
      path: '/learn/prediction'
      fullPath: '/learn/prediction'
      preLoaderRoute: typeof LearnPredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/positional-encoding': {
      id: '/learn/positional-encoding'
      path: '/learn/positional-encoding'
      fullPath: '/learn/positional-encoding'
      preLoaderRoute: typeof LearnPositionalEncodingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/neural-network': {
      id: '/learn/neural-network'
      path: '/learn/neural-network'
      fullPath: '/learn/neural-network'
      preLoaderRoute: typeof LearnNeuralNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/embeddings': {
      id: '/learn/embeddings'
      path: '/learn/embeddings'
      fullPath: '/learn/embeddings'
      preLoaderRoute: typeof LearnEmbeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/attention': {
      id: '/learn/attention'
      path: '/learn/attention'
      fullPath: '/learn/attention'
      preLoaderRoute: typeof LearnAttentionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CurriculumRoute: CurriculumRoute,
  LearnAttentionRoute: LearnAttentionRoute,
  LearnEmbeddingsRoute: LearnEmbeddingsRoute,
  LearnNeuralNetworkRoute: LearnNeuralNetworkRoute,
  LearnPositionalEncodingRoute: LearnPositionalEncodingRoute,
  LearnPredictionRoute: LearnPredictionRoute,
  LearnTokenizationRoute: LearnTokenizationRoute,
  LearnTrainingProcessRoute: LearnTrainingProcessRoute,
  LearnTransformerRoute: LearnTransformerRoute,
  LearnVisionRoute: LearnVisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
